language:
  - cpp

os:
  - linux

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Compile
  - BUILD_TYPE=Test

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-5
      - clang-3.6
      - libboost-all-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - lcov

before_install:
  - sudo pip install codecov
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6" CXXFLAGS="-Wno-return-type-c-linkage"; fi
  - git clone https://github.com/whoshuu/cpr.git /tmp/cpr
  - RESTORE_PWD="$PWD"
  - cd /tmp/cpr
  - git submodule init
  - git submodule update opt/mongoose/
  - mkdir build
  - cd build
  - cmake -DBUILD_CPR_TESTS=OFF -DUSE_SYSTEM_CURL=ON -DBUILD_CURL_TESTS=OFF -DCMAKE_CXX_FLAGS=-fPIC ..
  - make
  - cd "$RESTORE_PWD"

script:
  - mkdir -p build
  - cd build
  - $CXX --version
  - cmake --version
  - cmake -DMODULE_ALL=ON -DCPR_CUSTOM=ON -DCPR_INCLUDE=/tmp/cpr/include -DCPR_LIB=/tmp/cpr/build/lib ..
  - if [ "$BUILD_TYPE" = "Compile" ]; then make; fi
  - if [ "$BUILD_TYPE" = "Test" ]; then make test_all && cd test && ctest -V && lcov -c -d "$PWD" -b .. -o "coverage.info";  fi

after_success:
  - if [ "$BUILD_TYPE" = "Test" ]; then codecov; fi

notifications:
  irc:
    channels:
      - "irc.quakenet.org#eac.admin"
      - "irc.quakenet.org#melanosuchus"
    skip_join: true
    nick: MelanoTravis
