language:
  - cpp

os:
  - linux

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Compile
  - BUILD_TYPE=Test

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-5
      - clang-3.7
      - libboost-all-dev
      - libcurl4-openssl-dev
      - libssl-dev

before_install:
  - sudo pip install codecov

script:
  - mkdir -p build
  - cd build
  - if [ "$CXX" = "g++" ];     then export CXX="g++-5" CC="gcc-5";           fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - $CXX --version
  - cmake --version
  - cmake -DMODULE_ALL=ON ..
  - if [ "$BUILD_TYPE" = "Compile" ]; then make;                            fi
  - if [ "$BUILD_TYPE" = "Test" ];    then make test_all && make coverage;  fi

after_success:
  - if [ "$BUILD_TYPE" = "Test" ]; then codecov; fi

notifications:
  irc:
    - "irc.quakenet.org#eac.admin"
    - "irc.quakenet.org#melanosuchus"
  skip_join: true
