# Can be validated at http://lint.travis-ci.org/

language: cpp
compiler:
  - gcc
  - clang

script: mkdir build && cd build && cmake .. && make

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost1.55-dev libcurlpp-dev
